aws_access_key = "AKIAVDCNNPJRA7CCMZHF"
aws_secret_key = "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"
aws_bucket = "coversational-logging"
signature_version = "s3v4"
region_name = "eu-central-1"
db_name = "issm_db"
col_name = "convo_data"
mongo_link="mongodb+srv://alpha:dbuser123@cluster0.qyklj.mongodb.net/myFirstDatabase?retryWrites=true&w=majority"
